platform :ios, "7.0"

target "NSDate-TNSGregorianCalendar" do
    pod "NSDate-TNSGregorianCalendar", :path => "../NSDate-TNSGregorianCalendar.podspec"
end

target "NSDate-TNSGregorianCalendarTests" do
    pod "NSDate-TNSDateInitializer"
    pod "Kiwi/XCTest", "~> 2.2"
end
